职业: [
    "骑士",
    "战士",
    "暗骑",
    "枪刃",
    "白魔",
    "学者",
    "占星",
    "忍者",
    "龙骑",
    "武士",
    "武僧",
    "诗人",
    "机工",
    "黑魔",
    "召唤",
    "赤魔",
    "舞者",
    "钐镰客",
    "贤者",
    "捕鱼人",
    "厨师",
    "全部",
]

染料: [
    "特制金属橙染剂",
    "特制金属黄染剂",
    "金属橙染剂",
    "金属黄染剂",
    "特制黑暗红染剂",
    "特制黑暗棕染剂",
    "黑暗红染剂",
    "黑暗棕染剂",
    "特制黑暗绿染剂",
    "特制黑暗蓝染剂",
    "特制黑暗紫染剂",
    "特制金属蓝染剂",
    "特制金属紫染剂",
    "无瑕白染剂",
    "煤玉黑染剂",
    "闪耀银染剂",
    "闪耀金染剂",
    "柔彩粉染剂",
    "柔彩绿染剂",
    "黑暗绿染剂",
    "柔彩蓝染剂",
    "黑暗蓝染剂",
    "柔彩紫染剂",
    "黑暗紫染剂",
    "金属红染剂",
    "金属绿染剂",
    "金属蓝染剂",
    "金属靛染剂",
    "金属紫染剂",
    "特制柔彩粉染剂",
    "特制柔彩绿染剂",
    "特制柔彩蓝染剂",
    "特制柔彩紫染剂",
    "特制金属红染剂",
    "特制金属绿染剂",
    "特制金属靛染剂",
    "特制无瑕白染剂",
    "特制煤玉黑染剂",
    "特制闪耀银染剂",
    "特制闪耀金染剂",
    "珊瑚粉染剂",
    "软木棕染剂",
    "哥布林染剂",
    "苹果绿染剂",
    "金龟绿染剂",
    "罗海蓝染剂",
    "阴影蓝染剂",
    "虹膜紫染剂",
    "卢恩棕染剂",
    "橡果棕染剂",
    "萄干棕染剂",
    "仙人掌染剂",
    "绿松蓝染剂",
    "孔雀蓝染剂",
    "醋栗紫染剂",
    "丁香紫染剂",
    "黄沙棕染剂",
    "玉米黄染剂",
    "妖精绿染剂",
    "牧草绿染剂",
    "深林绿染剂",
    "天上蓝染剂",
    "腐尸蓝染剂",
    "靛青蓝染剂",
    "虚空蓝染剂",
    "薰衣草染剂",
    "蜂鸟粉染剂",
    "日落橙染剂",
    "钴铁棕染剂",
    "山羊棕染剂",
    "页岩棕染剂",
    "猛豹黄染剂",
    "青柠绿染剂",
    "沼泽绿染剂",
    "口花绿染剂",
    "海雾蓝染剂",
    "盗龙蓝染剂",
    "东洲蓝染剂",
    "风暴蓝染剂",
    "仙子梅染剂",
    "素雪白染剂",
    "石板灰染剂",
    "木炭灰染剂",
    "煤烟黑染剂",
    "罗兰莓染剂",
    "卫月红染剂",
    "铁锈红染剂",
    "果酒红染剂",
    "台地红染剂",
    "巧克力染剂",
    "铁锈棕染剂",
    "南瓜橙染剂",
    "山栗棕染剂",
    "沃土棕染剂",
    "沙漠黄染剂",
    "蜂蜜黄染剂",
    "奶油黄染剂",
    "橄榄绿染剂",
    "猎人绿染剂",
    "地神绿染剂",
    "魔花绿染剂",
    "油墨蓝染剂",
    "皇室蓝染剂",
    "午夜蓝染剂",
    "深渊蓝染剂",
    "葡萄紫染剂",
    "莲花粉染剂",
    "帝王紫染剂",
    "苍白灰染剂",
    "古菩灰染剂",
    "玫瑰粉染剂",
    "鲜血红染剂",
    "鲑鱼粉染剂",
    "树皮棕染剂",
    "奥猴棕染剂",
    "果园棕染剂",
    "鼹鼠棕染剂",
    "骸骨白染剂",
    "日影黄染剂",
    "泥沼绿染剂",
    "苔藓绿染剂",
    "寒冰蓝染剂",
    "天空蓝染剂",
    "青磷蓝染剂",
    "忧郁紫染剂",
    "宝石红染剂",
    "樱桃粉染剂",
    "丝雀黄染剂",
    "香草黄染剂",
    "龙骑蓝染剂",
    "松石蓝染剂",
    "炮铜黑染剂",
    "珍珠白染剂",
    "金属黄染剂",
    "全部染剂",
]

事件: [
    "诸事皆宜",
    "优雷卡",
    "博兹雅",
    "喷风",
    "刷外观",
    "找CP",
    "烙印",
    "偷情",
    "开荒",
    "打零式",
    "挂机",
    "挖宝",
    "采集",
    "钓鱼",
    "PVP",
    "随机任务",
    "装修",
    "截图",
    "练级",
    "危命任务",
    "炒股",
    "刷坐骑",
    "刷装备",
    "九宫幻卡",
    "多玛方城战",
    "赛鸟",
    "天宫死宫",
    "90002",
    "2002",
    "海钓",
    "烟波钓秃",
    "金蝶跳跳乐",
    "伊修加德重建",
    "库啵彩票",
    "极楼神",
    "极灯神",
    "义军武器",
    "快刀一闪",
    "幻巧拼图",
    "种西瓜",
    "搬家",
    "逛RP店",
    "种花",
    "乐器演奏",
]

宜:
  海钓: ["是时候双重提钩了", "幻海流与你有约", "《海王》"]
  库啵彩票: ["一等奖冲冲冲！", "获得了休闲外套装备箱"]
  伊修加德重建: ["伊修加德是一日建成的"]
  极楼神: ["你见过潮风亭楼顶的日落吗~"]
  炒股: ["你们炒股都不带我玩QAQ"]
  开荒: ["开荒记得要带我哦", "光之战士冲鸭！", "暗之战士冲鸭！"]
  诸事皆宜: ["萨纳兰今天也是艳阳高照啊", "美好的一天，适合挂机呢~"]
  钓鱼: ["红龙啊~红龙"]
  打蛮神: ["暗之战士冲鸭！"]
  截图: ["近朱者赤，近你者甜", "咔擦——", "自由探索模式出啦！冲！"]
  练级: ["努力成为全职业大佬！", "早日骑上阿马罗"]
  随机任务: ["今天会不会遇到可爱的豆芽呢？"]
  偷情: ["我听见雨滴落在青青草地~"]
  打零式: ["你要roll到武器箱子了！"]
  PVP: ["是...是狼王！"]
  优雷卡: ["凯西耳坠批发商就是你了！"]
  喷风: ["踏风无痕"]
  刷外观: ["心想事成"]
  找CP: ["蓦然回首，那人却在，灯火阑珊处。"]
  烙印: ["十二神的祝福与你同在"]
  挂机: ["芳景多游客，衰翁独板凳。"]
  挖宝: ["前沿布料批发商", "窥探未来"]
  采集: ["采集地点特效全触发！"]
  危命任务: ["双色宝石刷刷刷~"]
  刷坐骑: ["把把出坐骑，需求99"]
  九宫幻卡: ["是时候开卡包了！"]
  赛鸟: ["陆行鸟之歌.mp3"]
  天宫死宫: ["孤胆英雄/死灵术士在等着你"]
  2002: ["¿"]
  烟波钓秃: ["小楫扁舟乘兴出，斜风细雨钓鱼归。", "愿者上钩"]
  义军武器: ["是头秃的气息"]
  极灯神: ["精准降落"]
  搬家: ["空降海五(醒梦)"]
  装修: ["天才装修工！"]
  种花: ["别忘了施肥哦", "明天会不会收获白色光明百合花呢"]
  乐器演奏: ["一起来体会诗人的史诗级更新吧~", "DaLaDiDiDaLa"]
  博兹雅: ['获得了"发型样式：黎明辫"']
  幻巧拼图: ['目标："建筑06S号的核心"！']

忌:
  偷情: ["偷情要被发现啦，嘻嘻！"]
  伊修加德重建: ["藏狐盯————"]
  找CP: ["孤苦0仃，无1无靠"]
  打蛮神: ["躺在地上打副本，就是你了"]
  天宫死宫: ["宝箱变成了拟态怪"]
  打零式: ["四 大 名 著"]
  钓鱼: ["这里的鱼对你十分警惕~"]
  刷坐骑: ["图腾 x 99"]
  优雷卡: ["财宝好像在正北方向很远的地方"]
  喷风: ["获得了金碟币x100"]
  开荒: ["队友歼殛战", "给你开上地暖~"]
  挖宝: ["曲率引擎特快列车"]
  采集: ["林%"]
  随机任务: ["打满一个CD"]
  装修: ["装修悬浮后别忘了旋转哦~"]
  危命任务: ["危命任务失败了"]
  海钓: ["鱼王杆->提钩->莫莫拉"]
  2002: ["那就90002"]
  搬家: ["不宜动土"]
  极灯神: ["嗯哼？跳歪了"]
  种西瓜: ["亚拉戈西瓜已枯萎"]
  种花: ["褐色的土，黑色的花"]
  逛RP店: ["空空如也的招募板", "真可惜~RP店尚未开门"]
  截图: ["DirectX出现致命错误(耳语"]
  金蝶跳跳乐: ["又双叒叕掉下去了"]